name: pythonfiftyplus
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - pip:
    - RISE==5.7.1
    - ipynb==0.5.1
    - numpy==1.21
    - pandas==1.3
    - xlrd==2.0
    - openpyxl==3.0
    - scikit-learn==1.0